export const GET_FRIENDS_SUCCESS='GET_FRIENDS_SUCCESS'
export const GET_MESSAGES_SUCCESS='GET_MESSAGES_SUCCESS'
export const SEND_MESSAGES_SUCCESS='SEND_MESSAGES_SUCCESS'
export const SOCKET_SEND_MSG='SOCKET_SEND_MSG'
